---
- name: renovate/container
  color: "027fa0"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
- name: hold
  color: "ee0701"
- name: app/actions-runner
  color: 0e8a16
- name: app/bazarr
  color: 0e8a16
- name: app/buildarr
  color: 0e8a16
- name: app/home-assistant
  color: 0e8a16
- name: app/jbops
  color: 0e8a16
- name: app/lidarr
  color: 0e8a16
- name: app/par2cmdline-turbo
  color: 0e8a16
- name: app/plex
  color: 0e8a16
- name: app/postgres-init
  color: 0e8a16
- name: app/prowlarr
  color: 0e8a16
- name: app/qbittorrent
  color: 0e8a16
- name: app/radarr
  color: 0e8a16
- name: app/readarr
  color: 0e8a16
- name: app/sabnzbd
  color: 0e8a16
- name: app/sonarr
  color: 0e8a16
- name: app/theme-park
  color: 0e8a16
- name: app/volsync
  color: 0e8a16
